# Welcome to Jekyll!
#

# Site settings
title: Drupal Summer Barcelona
owner: Your Name # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Directories to include
include: ['_pages']

# Compress configuration to remove white spaces
# and line breaks
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

seo:
  default_image: /assets/images/seo-default.jpg

# Site languages: used for the language switcher
# first element is the default language
enabled_languages: ["ca", "en", "es"]

# Translations
t:
  ca:
    description: >
      El Drupal Summer Barcelona és un esdeveniment centrat en el Drupal per a
      potenciar-ne l’ús i interconnectar l’ecosistema d’empreses,
      desenvolupadors, dissenyadors, caps de projecte, usuaris i altres
      professionals, i alhora donar a conèixer l’ecosistema del Drupal local a
      fora.
    slogan:  El proper gran esdeveniment Drupal a Barcelona
    learn_more: descobreix més
    event_date: 7 - 9 juliol
    activate: activar
    landing_section1:
      title: Drupal 8 és aquí
      content: >
        Uneix-te a desenvolupadors, dissenyadors i drupalers durant 3 dies de
        sessions, sprints, formacions i activitats socials.

          El Drupal Summer Barcelona és un esdeveniment centrat en el Drupal
          per a potenciar-ne l’ús i interconnectar l’ecosistema d’empreses,
          desenvolupadors, dissenyadors, caps de projecte, usuaris i altres
          professionals, i alhora donar a conèixer l’ecosistema del Drupal local
          a fora.
    featured_speakers: Ponents destacats
    sponsors: Patrocinis

  en:
    description: >
      Drupal Summer Barcelona is an event which aims to promote the use of
      Drupal and to interconnect businesses, agencies, developers,
      designers, project managers, users and other professionals.
    slogan:  Next big Drupal event in Barcelona
    learn_more: discover more
    event_date: 7 - 9 july
    activate: activate
    landing_section1:
      title: Drupal 8 is here
      content: >
        Join developers, designers and drupalistas for two days of sessions,
        sprints,trainings and social activities.

          Drupal Summer Barcelona is an event which aims to promote the use
          of Drupal and to interconnect businesses, agencies, developers,
          designers, project managers, users and other professionals.
    featured_speakers: Featured speakers
    sponsors: Sponsors

  es:
    description: >
      El Drupal Summer Barcelona es un evento centrado en Drupal para potenciar
      su uso e interconectar el ecosistema de empresas, desarrolladores,
      diseñadores, jefes de proyecto, usuarios y otros profesionales, y a la vez
      dar a conocer el ecosistema de Drupal local fuera.
    slogan: El próximo gran evento Drupal en Barcelona
    learn_more: descubre más
    event_date: 7 - 9 julio
    activate: activar
    landing_section1:
      title: Drupal 8 está aquí
      content: >
        Únete a desarrolladores, diseñadores y drupaleros durante 3 días de
        sesiones, sprints, formaciones y actividades sociales.

          El Drupal Summer Barcelona es un evento centrado en Drupal para
          potenciar su uso e interconectar el ecosistema de empresas, desarrolladores,
          diseñadores, jefes de proyecto, usuarios y otros profesionales, y a la vez dar a
          conocer el ecosistema de Drupal local fuera.
    featured_speakers: Ponentes destacados
    sponsors: Patrocinios

# Main menu
main-menu:
  ca:
    - name: inici
      url: /ca/
    - name: ponents destacats
      url: "/ca/#speakers"
    - name: elements
      url:  /elements.html
    - name: patrocinadors
      url: "/ca/#sponsors"
    - name: codi de conducta
      url: /ca/codi-de-conducta/
  en:
    - name: home
      url: /en/
    - name: featured speakers
      url: "/en/#speakers"
    - name: elements
      url:  /elements.html
    - name: sponsors
      url: "/en/#sponsors"
    - name: code of conduct
      url: /en/code-of-conduct/
  es:
    - name: inicio
      url: /es/
    - name: ponenetes destacados
      url: "/es/#speakers"
    - name: elementos
      url:  /elements.html
    - name: patrocinadores
      url: "/es/#sponsors"
    - name: código de conducta
      url: /es/codigo-de-conducta/
