# Welcome to Jekyll!
#

# Site settings
title: Drupal Summer Barcelona
owner: Drupal.cat # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: esdeveniments@drupal.cat
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://summer2017.drupal.cat" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/drupalsummer
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Directories to include
include: ['_pages']

# Compress configuration to remove unnecessary 
# white spaces and line breaks
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

seo:
  default_image: /assets/images/seo-default.jpg

# Site languages: used for the language switcher
# first element is the default language
enabled_languages: ["ca", "en", "es"]

# Main menu
main-menu:
  ca:
    - name: inici
      url: /ca/
#    - name: ponents destacats
#      url: "/ca/#speakers"
#    - name: elements
#      url:  /elements.html
    - name: patrocinadors
      url: "/ca/#sponsors"
    - name: codi de conducta
      url: /ca/codi-de-conducta/
  en:
    - name: home
      url: /en/
#    - name: featured speakers
#      url: "/en/#speakers"
#    - name: elements
#      url:  /elements.html
    - name: sponsors
      url: "/en/#sponsors"
    - name: code of conduct
      url: /en/code-of-conduct/
  es:
    - name: inicio
      url: /es/
#   - name: ponenetes destacados
#     url: "/es/#speakers"
#   - name: elementos
#     url:  /elements.html
    - name: patrocinadores
      url: "/es/#sponsors"
    - name: código de conducta
      url: /es/codigo-de-conducta/
