# Welcome to Jekyll!
#

# Site settings
title: Drupal Summer Barcelona
owner: Drupal.cat # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: esdeveniments@drupal.cat
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://summer2017.drupal.cat" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/drupalsummer
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: "mailto:esdeveniments@drupal.cat"
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# social media share enabled
social-share:
  facebook: true
  twitter: true
  google_plus: true
  instagram: true

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Directories to include
include:
  - _pages

# Directories and files to exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - _app
  - gulpfile.js
  - node_modules
  - package.json

# Compress configuration to remove unnecessary
# white spaces and line breaks
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

seo:
  default_image: /assets/images/default-seo-img.png

# Site languages: used for the language switcher
# first element is the default language
enabled_languages: ["ca", "en", "es"]

# Main menu
main-menu:
  ca:
    - name: inici
      url: /ca/
    - name: ponents destacats
      url: "/ca/#speakers"
      #    - name: elements
      #      url:  /elements.html
    - name: Programa
      url: "/ca/programa/"
    - name: Sessions
      url: "/ca/programa/dissabte/"
    - name: Summer party!
      url: /ca/summer-party/
    - name: patrocinadors
      url: "/ca/#sponsors"
    - name: badges
      url: "/ca/badges/"
    - name: codi de conducta
      url: /ca/codi-de-conducta/
    - name: Foto de grup
      url: "/ca/foto-de-grup/"
  en:
    - name: home
      url: /en/
    - name: Schedule
      url: "/en/schedule/"
    - name: Sessions
      url: "/en/schedule/saturday/"
    - name: Summer party!
      url: /en/summer-party/
    - name: featured speakers
      url: "/en/#speakers"
      #    - name: elements
      #      url:  /elements.html
    - name: sponsors
      url: "/en/#sponsors"
    - name: badges
      url: "/en/badges/"
    - name: code of conduct
      url: /en/code-of-conduct/
    - name: Group photo
      url: "/en/group-photo/"
  es:
    - name: inicio
      url: /es/
    - name: Programa
      url: "/es/programa/"
    - name: Sesiones
      url: "/es/programa/sabado/"
    - name: Summer party!
      url: /es/summer-party/
    - name: ponenetes destacados
      url: "/es/#speakers"
      #   - name: elementos
      #     url:  /elements.html
    - name: patrocinadores
      url: "/es/#sponsors"
    - name: badges
      url: "/es/badges/"
    - name: código de conducta
      url: /es/codigo-de-conducta/
    - name: Foto de grupo
      url: "/es/foto-de-grupo/"
