# Welcome to Jekyll!
#

# Site settings
title: Spectral multilingual
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Your Name # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Directories to include
include: ['_pages']

# Compress configuration to remove white spaces
# and line breaks
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []


# Site languages: used for the language switcher
# first element is the default language
enabled_languages: ["ca", "en", "es"]

# Translations
t:
  ca:
    description: >
      Descripció català
      
    event_date: XX-YY mes
    discover_more: descobreix més
  en:
    description: >
      Description english
    event_date: XX-YY month
    discover_more: discover more
  es:
    description: >
      Descripción castellano
    event_date: XX-YY mes
    discover_more: descubre más

# Main menu
main-menu:
  ca:
    - name: inici
      url: /ca/
    - name: qui som
      url: /ca/qui-som/
    - name: elements
      url:  /elements.html
  en:
    - name: home
      url: /en/
    - name: about us
      url: /es/about/
    - name: elements
      url:  /elements.html
  es:
    - name: inicio
      url: /es/
    - name: sobre nosotros
      url: /es/sobre-nosotros/
    - name: elementos
      url:  /elements.html
